### ISSUE TITLE
Crash when running opt with parameters removed from opt

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn#106]
@kohl-carmen reported the following crash trying to run parameter optimization when some parameters have been disabled for optimization.

Traceback (most recent call last):
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 2448, in updatesaveparams
    for win in self.lsubwin: win.setfromdin(dtest)
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 1831, in setfromdin
    self.updateDispRanges()
  File "C:\Users\ckohl\hnn\hnn_qt5.py", line 1755, in updateDispRanges
    initial_value = float(self.initial_opt_info[tab_index][label]['initial'])
KeyError: 'gbar_evprox_1_L2Pyr_ampa'

**Comment by blakecaldwell** [comment]
New failure introduced by #107 
```
Traceback (most recent call last):
  File "C:\Users\caldw\repos\hnn\hnn_qt5.py", line 2590, in selParamFileDialog
    self.baseparamwin.updateDispParam()
  File "C:\Users\caldw\repos\hnn\hnn_qt5.py", line 2313, in updateDispParam
    for dlg in self.lsubwin: dlg.setfromdin(din) # update to values from file
  File "C:\Users\caldw\repos\hnn\hnn_qt5.py", line 1801, in setfromdin
    self.removeAllInputs() # turn off any previously set inputs
  File "C:\Users\caldw\repos\hnn\hnn_qt5.py", line 1109, in removeAllInputs
    for i in range(len(self.ltabs)): self.removeCurrentInput()
  File "C:\Users\caldw\repos\hnn\hnn_qt5.py", line 1198, in removeCurrentInput
    self.removeInput(idx)
  File "C:\Users\caldw\repos\hnn\hnn_qt5.py", line 1176, in removeInput
    if k in self.dqline:
AttributeError: 'OptEvokedInputParamDialog' object has no attribute 'dqline'
```
